pipeline {
  agent any

  stages {

    stage('Clone Repo') {
      steps {
        git 'https://github.com/<your-username>/single-ec2-devops-cicd.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t devops-app app/'
      }
    }

    stage('Push Docker Image') {
      steps {
        sh '''
        docker tag devops-app <dockerhub-username>/devops-app
        docker push <dockerhub-username>/devops-app
        '''
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh 'kubectl apply -f kubernetes/'
      }
    }
  }
}
